#ifndef __PointSource_H_
#define __PointSource_H_ 1

#include "Source.hh"

/** Source with defined position and enrgy that generates gammas only in that
 * point with that energy
 */
class PointSource : public Source {
public:
  PointSource() = default;
  /** Create point surce
   * \param position source position
   * \param energy initial energy of particles generated by this source.
   */
  PointSource(const TVector3& position, Double_t energy)
      : Source(position), fEnergy(energy){};
  
  PointSource(const TString& fname)
      :  fInFileName(fname){};

  /** Generate particle */
  Track GenerateEvent() override;

  void Print(void);

private:
  /** Init() initializes source properties based on configuration file */
  virtual Bool_t Init() override;

  ClassDef(PointSource, 1)
};

#endif
